---
title: "About the Sauces"
---

All three hot sauces were made by fermenting home grown chili peppers with other select ingredients ([see ingredients here](ingredients.html)).  Peppers and other vegetable ingredients were chopped finely and mashed with salt (3% by weight), allowed to ferment for two weeks, then stabilized with vinegar and additional spices.  Additional fermentation may occur slowly – keep refrigerated.

The Fatalii Fuyu sauce starts with home-grown Fatalii peppers (_Capsicum chinense_), which are between 150,000 and 400,000 [Scoville Heat Units](https://www.chilipeppermadness.com/frequently-asked-questions/the-scoville-scale/){target='_blank'} (SHU - for reference, jalapenos are 3,000 to 5,000 SHU).  These are blended with home grown fuyu persimmons and bell peppers, and this sauce boasts a bright tropical flavor with its heat.  The fruit and bell peppers mellow the spice of the Fatalii, so I expect this sauce is probably around 50,000-75,000 SHU.  This is about 15-20 times hotter than Tabasco^TM^ (about 3,500 SHU).  If you're a fan of the [Hot Ones YouTube series](https://www.youtube.com/playlist?list=PLAzrgbu8gEMIIK3r4Se1dOZWSZzUSadfZ){target='_blank'}, this would put it around #6 in the lineup.

The Tabasco 2.0 sauce is a mash of only home-grown Tabasco peppers (_Capsicum frutescens_) and a little garlic, so you get the full essence of this delicious chili pepper.  Tabasco peppers are less spicy than Fatalii (around 30,000-50,000 SHU) but these are not diluted with fruits or mild peppers, so this sauce will be far hotter than store-bought Tabasco^TM^.  Even so, I expect this sauce is probably around 20,000-30,000 SHU, probably only around #3 or #4 in a [Hot Ones](https://www.youtube.com/playlist?list=PLAzrgbu8gEMIIK3r4Se1dOZWSZzUSadfZ){target='_blank'} lineup...

The Plum Habanero sauce combines home-grown plums with an assortment of home grown habanero varieties (_Capsicum chinense_).  A little cumin and garlic gives some earthy notes to this tangy, sweet sauce.  Habaneros are similar to Fatalii in terms of heat, so this sauce will be similar in heat to the Fatalii Fuyu, probably around 50,000-75,000 SHU.

Home grown chili peppers were grown with only organic fertilizers and pesticides.  Most other vegetables are also organic.  All sauces are vegan and gluten free, but made on home kitchen equipment.

Try these sauces on eggs, tacos, pasta, burgers, pizza, whatever you like!  To get a good sense of the flavors, I like to pour some of the spicy stuff into an avocado half, and mash it a little and eat it with a spoon – the avocado dramatically mellows the heat.

